export const REQUEST_TRIVIA_API = 'REQUEST_TRIVIA_API';

export const REQUEST_TRIVIA_API_SUCESS = 'REQUEST_TRIVIA_API_SUCESS';

export const REQUEST_TRIVIA_API_FAILURE = 'REQUEST_TRIVIA_API_FAILURE';

export const REQUEST_TOKEN = 'REQUEST_TOKEN';
